### ISSUE TITLE
Chances for Godot 3.1.2 and Godot 3.2?

### ISSUE THREAD

**Issue by Tobi-La** [GhostWalker562/godot-admob-iOS-precompiled#2]
Hey,
thank you so much for your precompiled templates, they saved me a lot of time!
Is there a chance you're doing the same for godot 3.1.2?

And what are the chances for 3.2 once it's out in the next month?

Thanks,
Tobi

**Comment by GhostWalker562** [comment]
looking to recompile today, sorry for the delay.

**Comment by GhostWalker562** [comment]
The template has been compiled, for 3.2 for today.
