### ISSUE TITLE
3.2 template?

### ISSUE THREAD

**Issue by sp00mm** [GhostWalker562/godot-admob-iOS-precompiled#3]
Thanks for the templates!

I was going to try to compile one myself for 3.2 but it looks like you need Xcode 10.x to do so. I'm still on 8.x and HS but can't upgrade because I'm running an Nvidia card.

Are you planning on making a new one?

Thanks!
Austin

**Comment by GhostWalker562** [comment]
Looking to recompile today, sorry for the delay.

**Comment by GhostWalker562** [comment]
The template has been compiled.
