### ISSUE TITLE
[SUGGESTION] Create a demo of the usage of plugin

### ISSUE THREAD

**Issue by gustavottc** [GhostWalker562/godot-admob-iOS-precompiled#6]
Please create a demo to demonstrate how to avoid this error: Multiple locks on web thread not allowed

**Comment by GhostWalker562** [comment]
There is a work around commented here, https://github.com/kloder-games/godot-admob/issues/53#issuecomment-503150429 . Not sure if this is relevant but I believe looking at this would help.
