### ISSUE TITLE
Adding more modules?

### ISSUE THREAD

**Issue by CompassDevs** [GhostWalker562/godot-admob-iOS-precompiled#8]
Hey There, is any chances to add in the latest pre-compiled Admob for ios also vibrate and share, like the one for android?

**Comment by GhostWalker562** [comment]
Sure thing, I’ll try to get it done tomorrow.

**Comment by CompassDevs** [comment]
Great, so Admob,vibrate and share all in one template (debug/release) for iOS. You are a life saver...

**Comment by GhostWalker562** [comment]
I released a version of the admob compiled template 3.2.1 with the shared module. Vibrate has been added to the latest version of Godot already so I didn't add the module. Thank you👯‍♂️

**Comment by CompassDevs** [comment]
I got all of these errors.....
